version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: npm
    directory: "/adventure_allies"
    schedule:
      interval: "daily"
  - package-ecosystem: 	docker
    directory: "/"
    schedule:
      interval: "daily"